### ISSUE TITLE
[*] Error Status Code :  'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by dave-tree-uk** [sunnypatell/sunnify-spotify-downloader#3]
Getting this error on several songs that are being downloaded. 

Example of a track which fails:
Artist: "PEZ" 
Song: "This sound" 
Album: "A mind of my own"

**Comment by sunnypatell** [comment]
Hey Dave,

If you're only encountering this issue with certain songs and not the entire playlist, it’s likely that the API used to scrape the music database doesn’t have those specific tracks, so it can't find a corresponding YouTube ID with the same suffix. I've just tested and it still works.

Try using a more popular playlist and see if the issue persists.

**Comment by sunnypatell** [comment]
## Update: v2.0.0 Released 🎉

The underlying API issue has been fixed in **v2.0.0**. The old spotifydown mirrors are no longer used.

**What changed:**
- Switched to Spotify's embed page API (`/embed/playlist/{id}`, `/embed/track/{id}`)
- No authentication or credentials required
- Supports playlists >100 tracks via spclient fallback
- Single track downloads now supported

**Get the update:**
- Download pre-built apps: https://github.com/sunnypatell/sunnify-spotify-downloader/releases/latest
- Or pull latest and run: `pip install -r req.txt && python Spotify_Downloader.py`

All API endpoints are working as of this update. Run `python scripts/check_api_status.py` to verify.
